export { ReactComponent as LogoIcon } from './logo.svg'
export { ReactComponent as LoginLogoIcon } from './login_logo.svg'
export { ReactComponent as LoginImgIcon } from './login_img.svg'
export { ReactComponent as MenuBtnIcon } from './menu_btn.svg'
export { ReactComponent as CloseArrowBtnIcon } from './close_arrow_btn.svg'
export { ReactComponent as CloseBtnIcon } from './close_btn.svg'
export { ReactComponent as AddFileIcon } from './add_file.svg'
